# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  bb84homeapi:
    image: bb84homeapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 443:443
