//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("https://github.com/BoBoBaSs84")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2023 BoBoBaSs84")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("This is just an attempt to have a clean base architecture for database access.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2023.6.27.913")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2023.6.27.913-dev")]
[assembly: System.Reflection.AssemblyProductAttribute("EF.Core.Database.Adapter")]
[assembly: System.Reflection.AssemblyTitleAttribute("Presentation")]
[assembly: System.Reflection.AssemblyVersionAttribute("2023.6.27.913")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/BoBoBaSs84/EF.Core.Database.Adapter")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("en-US")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Presentation.Tests")]

// Generated by the MSBuild WriteCodeFragment class.

