//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumeratorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumeratorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Properties.EnumeratorResources", typeof(EnumeratorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is an authorised prolonged absence from work, for any reason authorised by the workplace..
        /// </summary>
        public static string AttendanceType_Absence_Description {
            get {
                return ResourceManager.GetString("AttendanceType.Absence.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence.
        /// </summary>
        public static string AttendanceType_Absence_Name {
            get {
                return ResourceManager.GetString("AttendanceType.Absence.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB.
        /// </summary>
        public static string AttendanceType_Absence_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.Absence.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business travel is travel undertaken for work or business purposes, as opposed to other types of travel, such as for leisure purposes..
        /// </summary>
        public static string AttendanceType_BuisnessTrip_Description {
            get {
                return ResourceManager.GetString("AttendanceType.BuisnessTrip.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buisness trip.
        /// </summary>
        public static string AttendanceType_BuisnessTrip_Name {
            get {
                return ResourceManager.GetString("AttendanceType.BuisnessTrip.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BT.
        /// </summary>
        public static string AttendanceType_BuisnessTrip_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.BuisnessTrip.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A holiday is a day set aside by custom or by law on which normal activities, especially business or work including school, are suspended or reduced..
        /// </summary>
        public static string AttendanceType_Holiday_Description {
            get {
                return ResourceManager.GetString("AttendanceType.Holiday.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string AttendanceType_Holiday_Name {
            get {
                return ResourceManager.GetString("AttendanceType.Holiday.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD.
        /// </summary>
        public static string AttendanceType_Holiday_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.Holiday.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The place of work is usually in the employee&apos;s own home, and in the case of mobile work also in third locations..
        /// </summary>
        public static string AttendanceType_MobileWorking_Description {
            get {
                return ResourceManager.GetString("AttendanceType.MobileWorking.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile working.
        /// </summary>
        public static string AttendanceType_MobileWorking_Name {
            get {
                return ResourceManager.GetString("AttendanceType.MobileWorking.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW.
        /// </summary>
        public static string AttendanceType_MobileWorking_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.MobileWorking.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is either the plan to leave of absence from a regular job or an instance of leisure travel away from home..
        /// </summary>
        public static string AttendanceType_PlannedVacation_Description {
            get {
                return ResourceManager.GetString("AttendanceType.PlannedVacation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned vacation.
        /// </summary>
        public static string AttendanceType_PlannedVacation_Name {
            get {
                return ResourceManager.GetString("AttendanceType.PlannedVacation.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV.
        /// </summary>
        public static string AttendanceType_PlannedVacation_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.PlannedVacation.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-time work in the employment relationship means the temporary reduction of regular working hours in a company due to a significant loss of work..
        /// </summary>
        public static string AttendanceType_ShortTimeWork_Description {
            get {
                return ResourceManager.GetString("AttendanceType.ShortTimeWork.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short time work.
        /// </summary>
        public static string AttendanceType_ShortTimeWork_Name {
            get {
                return ResourceManager.GetString("AttendanceType.ShortTimeWork.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST.
        /// </summary>
        public static string AttendanceType_ShortTimeWork_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.ShortTimeWork.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee can no longer perform his or her most recently performed work tasks due to illness or can only do so at the risk of aggravating the illness..
        /// </summary>
        public static string AttendanceType_Sickness_Description {
            get {
                return ResourceManager.GetString("AttendanceType.Sickness.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sickness.
        /// </summary>
        public static string AttendanceType_Sickness_Name {
            get {
                return ResourceManager.GetString("AttendanceType.Sickness.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        public static string AttendanceType_Sickness_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.Sickness.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the case of a suspension, the employee is permanently or temporarily released from his or her contractual work duties..
        /// </summary>
        public static string AttendanceType_Suspension_Description {
            get {
                return ResourceManager.GetString("AttendanceType.Suspension.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension.
        /// </summary>
        public static string AttendanceType_Suspension_Name {
            get {
                return ResourceManager.GetString("AttendanceType.Suspension.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP.
        /// </summary>
        public static string AttendanceType_Suspension_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.Suspension.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is either a leave of absence from a regular job or an instance of leisure travel away from home..
        /// </summary>
        public static string AttendanceType_Vacation_Description {
            get {
                return ResourceManager.GetString("AttendanceType.Vacation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        public static string AttendanceType_Vacation_Name {
            get {
                return ResourceManager.GetString("AttendanceType.Vacation.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC.
        /// </summary>
        public static string AttendanceType_Vacation_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.Vacation.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the vacation block, employers prohibit their employees from taking vacation during a certain period of time..
        /// </summary>
        public static string AttendanceType_VacationBlock_Description {
            get {
                return ResourceManager.GetString("AttendanceType.VacationBlock.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation block.
        /// </summary>
        public static string AttendanceType_VacationBlock_Name {
            get {
                return ResourceManager.GetString("AttendanceType.VacationBlock.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB.
        /// </summary>
        public static string AttendanceType_VacationBlock_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.VacationBlock.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day on which professional work is performed or is to be performed..
        /// </summary>
        public static string AttendanceType_Workday_Description {
            get {
                return ResourceManager.GetString("AttendanceType.Workday.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workday.
        /// </summary>
        public static string AttendanceType_Workday_Name {
            get {
                return ResourceManager.GetString("AttendanceType.Workday.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WK.
        /// </summary>
        public static string AttendanceType_Workday_ShortName {
            get {
                return ResourceManager.GetString("AttendanceType.Workday.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A credit card is a payment card issued to users to enable the cardholder to pay a merchant for goods and services based on the cardholder&apos;s accrued debt..
        /// </summary>
        public static string CardType_Credit_Description {
            get {
                return ResourceManager.GetString("CardType.Credit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card.
        /// </summary>
        public static string CardType_Credit_Name {
            get {
                return ResourceManager.GetString("CardType.Credit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string CardType_Credit_ShortName {
            get {
                return ResourceManager.GetString("CardType.Credit.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A debit card, also known as a check card or bank card is a payment card that can be used in place of cash to make purchases..
        /// </summary>
        public static string CardType_Debit_Description {
            get {
                return ResourceManager.GetString("CardType.Debit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit card.
        /// </summary>
        public static string CardType_Debit_Name {
            get {
                return ResourceManager.GetString("CardType.Debit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string CardType_Debit_ShortName {
            get {
                return ResourceManager.GetString("CardType.Debit.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of multiple sources..
        /// </summary>
        public static string ErrorTypes_Composite_Description {
            get {
                return ResourceManager.GetString("ErrorTypes.Composite.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite.
        /// </summary>
        public static string ErrorTypes_Composite_Name {
            get {
                return ResourceManager.GetString("ErrorTypes.Composite.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        public static string ErrorTypes_Composite_ShortName {
            get {
                return ResourceManager.GetString("ErrorTypes.Composite.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that the request could not be processed because of conflict in the request, such as the requested resource is not in the expected state..
        /// </summary>
        public static string ErrorTypes_Conflict_Description {
            get {
                return ResourceManager.GetString("ErrorTypes.Conflict.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        public static string ErrorTypes_Conflict_Name {
            get {
                return ResourceManager.GetString("ErrorTypes.Conflict.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO.
        /// </summary>
        public static string ErrorTypes_Conflict_ShortName {
            get {
                return ResourceManager.GetString("ErrorTypes.Conflict.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the server unexpectedly fails to respond to the sent request..
        /// </summary>
        public static string ErrorTypes_Failure_Description {
            get {
                return ResourceManager.GetString("ErrorTypes.Failure.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string ErrorTypes_Failure_Name {
            get {
                return ResourceManager.GetString("ErrorTypes.Failure.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA.
        /// </summary>
        public static string ErrorTypes_Failure_ShortName {
            get {
                return ResourceManager.GetString("ErrorTypes.Failure.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals to the client that the requested data is access-protected and the request cannot be performed due to a lack of authorization on the part of the client..
        /// </summary>
        public static string ErrorTypes_Forbidden_Description {
            get {
                return ResourceManager.GetString("ErrorTypes.Forbidden.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string ErrorTypes_Forbidden_Name {
            get {
                return ResourceManager.GetString("ErrorTypes.Forbidden.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FO.
        /// </summary>
        public static string ErrorTypes_Forbidden_ShortName {
            get {
                return ResourceManager.GetString("ErrorTypes.Forbidden.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indicates that a request has succeeded, but that the client doesn&apos;t need to navigate away from its current page..
        /// </summary>
        public static string ErrorTypes_NoContent_Description {
            get {
                return ResourceManager.GetString("ErrorTypes.NoContent.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoContent.
        /// </summary>
        public static string ErrorTypes_NoContent_Name {
            get {
                return ResourceManager.GetString("ErrorTypes.NoContent.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC.
        /// </summary>
        public static string ErrorTypes_NoContent_ShortName {
            get {
                return ResourceManager.GetString("ErrorTypes.NoContent.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that the requested resource does not exist on the server..
        /// </summary>
        public static string ErrorTypes_NotFound_Description {
            get {
                return ResourceManager.GetString("ErrorTypes.NotFound.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        public static string ErrorTypes_NotFound_Name {
            get {
                return ResourceManager.GetString("ErrorTypes.NotFound.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NF.
        /// </summary>
        public static string ErrorTypes_NotFound_ShortName {
            get {
                return ResourceManager.GetString("ErrorTypes.NotFound.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the status code to return when the client provides no credentials or invalid credentials..
        /// </summary>
        public static string ErrorTypes_Unauthorized_Description {
            get {
                return ResourceManager.GetString("ErrorTypes.Unauthorized.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string ErrorTypes_Unauthorized_Name {
            get {
                return ResourceManager.GetString("ErrorTypes.Unauthorized.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA.
        /// </summary>
        public static string ErrorTypes_Unauthorized_ShortName {
            get {
                return ResourceManager.GetString("ErrorTypes.Unauthorized.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client error response code indicates that the expectation given in the request..
        /// </summary>
        public static string ErrorTypes_Unexpected_Description {
            get {
                return ResourceManager.GetString("ErrorTypes.Unexpected.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected.
        /// </summary>
        public static string ErrorTypes_Unexpected_Name {
            get {
                return ResourceManager.GetString("ErrorTypes.Unexpected.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UE.
        /// </summary>
        public static string ErrorTypes_Unexpected_ShortName {
            get {
                return ResourceManager.GetString("ErrorTypes.Unexpected.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that the server cannot or will not process the request due to something that is perceived to be a client error..
        /// </summary>
        public static string ErrorTypes_Validation_Description {
            get {
                return ResourceManager.GetString("ErrorTypes.Validation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string ErrorTypes_Validation_Name {
            get {
                return ResourceManager.GetString("ErrorTypes.Validation.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA.
        /// </summary>
        public static string ErrorTypes_Validation_ShortName {
            get {
                return ResourceManager.GetString("ErrorTypes.Validation.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the ultimate god role ... so to say..
        /// </summary>
        public static string RoleType_Administrator_Description {
            get {
                return ResourceManager.GetString("RoleType.Administrator.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string RoleType_Administrator_Name {
            get {
                return ResourceManager.GetString("RoleType.Administrator.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADM.
        /// </summary>
        public static string RoleType_Administrator_ShortName {
            get {
                return ResourceManager.GetString("RoleType.Administrator.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with extended user rights..
        /// </summary>
        public static string RoleType_SuperUser_Description {
            get {
                return ResourceManager.GetString("RoleType.SuperUser.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super user.
        /// </summary>
        public static string RoleType_SuperUser_Name {
            get {
                return ResourceManager.GetString("RoleType.SuperUser.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUSR.
        /// </summary>
        public static string RoleType_SuperUser_ShortName {
            get {
                return ResourceManager.GetString("RoleType.SuperUser.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a normal user with normal user rights..
        /// </summary>
        public static string RoleType_User_Description {
            get {
                return ResourceManager.GetString("RoleType.User.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string RoleType_User_Name {
            get {
                return ResourceManager.GetString("RoleType.User.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USR.
        /// </summary>
        public static string RoleType_User_ShortName {
            get {
                return ResourceManager.GetString("RoleType.User.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday is the day of the week between Thursday and Saturday. In countries that adopt the traditional &quot;Sunday-first&quot; convention, it is the sixth day of the week..
        /// </summary>
        public static string WorkDayTypes_Friday_Description {
            get {
                return ResourceManager.GetString("WorkDayTypes.Friday.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string WorkDayTypes_Friday_Name {
            get {
                return ResourceManager.GetString("WorkDayTypes.Friday.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRI.
        /// </summary>
        public static string WorkDayTypes_Friday_ShortName {
            get {
                return ResourceManager.GetString("WorkDayTypes.Friday.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday is the day of the week that takes place between Sunday and Tuesday.[1] According to the International Organization for Standardization&apos;s ISO 8601 standard, it is the first day of the week..
        /// </summary>
        public static string WorkDayTypes_Monday_Description {
            get {
                return ResourceManager.GetString("WorkDayTypes.Monday.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string WorkDayTypes_Monday_Name {
            get {
                return ResourceManager.GetString("WorkDayTypes.Monday.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MON.
        /// </summary>
        public static string WorkDayTypes_Monday_ShortName {
            get {
                return ResourceManager.GetString("WorkDayTypes.Monday.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday is the day of the week between Friday and Sunday..
        /// </summary>
        public static string WorkDayTypes_Saturday_Description {
            get {
                return ResourceManager.GetString("WorkDayTypes.Saturday.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string WorkDayTypes_Saturday_Name {
            get {
                return ResourceManager.GetString("WorkDayTypes.Saturday.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAT.
        /// </summary>
        public static string WorkDayTypes_Saturday_ShortName {
            get {
                return ResourceManager.GetString("WorkDayTypes.Saturday.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday is the day of the week between Saturday and Monday. In most Western countries, Sunday is a day of rest and a part of the weekend..
        /// </summary>
        public static string WorkDayTypes_Sunday_Description {
            get {
                return ResourceManager.GetString("WorkDayTypes.Sunday.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string WorkDayTypes_Sunday_Name {
            get {
                return ResourceManager.GetString("WorkDayTypes.Sunday.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUN.
        /// </summary>
        public static string WorkDayTypes_Sunday_ShortName {
            get {
                return ResourceManager.GetString("WorkDayTypes.Sunday.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday is the day of the week between Wednesday and Friday. According to the ISO 8601 international standard, it is the fourth day of the week..
        /// </summary>
        public static string WorkDayTypes_Thursday_Description {
            get {
                return ResourceManager.GetString("WorkDayTypes.Thursday.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string WorkDayTypes_Thursday_Name {
            get {
                return ResourceManager.GetString("WorkDayTypes.Thursday.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THU.
        /// </summary>
        public static string WorkDayTypes_Thursday_ShortName {
            get {
                return ResourceManager.GetString("WorkDayTypes.Thursday.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday is the day of the week between Monday and Wednesday. According to international standard ISO 8601, it is the second day of the week..
        /// </summary>
        public static string WorkDayTypes_Tuesday_Description {
            get {
                return ResourceManager.GetString("WorkDayTypes.Tuesday.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string WorkDayTypes_Tuesday_Name {
            get {
                return ResourceManager.GetString("WorkDayTypes.Tuesday.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUE.
        /// </summary>
        public static string WorkDayTypes_Tuesday_ShortName {
            get {
                return ResourceManager.GetString("WorkDayTypes.Tuesday.ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday is the day of the week between Tuesday and Thursday. According to international standard ISO 8601, it is the third day of the week..
        /// </summary>
        public static string WorkDayTypes_Wednesday_Description {
            get {
                return ResourceManager.GetString("WorkDayTypes.Wednesday.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string WorkDayTypes_Wednesday_Name {
            get {
                return ResourceManager.GetString("WorkDayTypes.Wednesday.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WED.
        /// </summary>
        public static string WorkDayTypes_Wednesday_ShortName {
            get {
                return ResourceManager.GetString("WorkDayTypes.Wednesday.ShortName", resourceCulture);
            }
        }
    }
}
