//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Properties.ServiceErrors", typeof(ServiceErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bank account with the identifier: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string AccountService_AccountId_NotFound {
            get {
                return ResourceManager.GetString("AccountService.AccountId.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account with the number: &apos;{0}&apos; already exists..
        /// </summary>
        public static string AccountService_AccountNumber_Conflict {
            get {
                return ResourceManager.GetString("AccountService.AccountNumber.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bank account with the number: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string AccountService_AccountNumber_NotFound {
            get {
                return ResourceManager.GetString("AccountService.AccountNumber.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No card with the identifier: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string AccountService_CardId_NotFound {
            get {
                return ResourceManager.GetString("AccountService.CardId.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card with the number: &apos;{0}&apos; already exists..
        /// </summary>
        public static string AccountService_CardNumber_Conflict {
            get {
                return ResourceManager.GetString("AccountService.CardNumber.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No card type with the identifier: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string AccountService_CardTypeId_NotFound {
            get {
                return ResourceManager.GetString("AccountService.CardTypeId.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An guidernal error occurred while creating the account..
        /// </summary>
        public static string AccountService_Create_Failed {
            get {
                return ResourceManager.GetString("AccountService.Create.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An guidernal error occurred while deleting the account..
        /// </summary>
        public static string AccountService_Delete_Failed {
            get {
                return ResourceManager.GetString("AccountService.Delete.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the bank accounts..
        /// </summary>
        public static string AccountService_GetAll_Failed {
            get {
                return ResourceManager.GetString("AccountService.GetAll.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bank accounts could be found to load..
        /// </summary>
        public static string AccountService_GetAll_NotFound {
            get {
                return ResourceManager.GetString("AccountService.GetAll.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the bank account with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string AccountService_GetById_Failed {
            get {
                return ResourceManager.GetString("AccountService.GetById.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the bank account with the number: &apos;{0}&apos;..
        /// </summary>
        public static string AccountService_GetByNumber_Failed {
            get {
                return ResourceManager.GetString("AccountService.GetByNumber.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An guidernal error occurred while updating the account..
        /// </summary>
        public static string AccountService_Update_Failed {
            get {
                return ResourceManager.GetString("AccountService.Update.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors in the create request, please check and correct..
        /// </summary>
        public static string AttendanceService_Create_BadRequest {
            get {
                return ResourceManager.GetString("AttendanceService.Create.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry with the date &apos;{0}&apos; has already been created..
        /// </summary>
        public static string AttendanceService_Create_Conflict {
            get {
                return ResourceManager.GetString("AttendanceService.Create.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the attendance/absence..
        /// </summary>
        public static string AttendanceService_Create_Failed {
            get {
                return ResourceManager.GetString("AttendanceService.Create.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No calendar entry with the date &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string AttendanceService_Create_NotFound {
            get {
                return ResourceManager.GetString("AttendanceService.Create.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the attendances/absences..
        /// </summary>
        public static string AttendanceService_CreateMany_Failed {
            get {
                return ResourceManager.GetString("AttendanceService.CreateMany.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the attendance/absence..
        /// </summary>
        public static string AttendanceService_Delete_Failed {
            get {
                return ResourceManager.GetString("AttendanceService.Delete.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The presence/absence which should be deleted could not be found..
        /// </summary>
        public static string AttendanceService_Delete_NotFound {
            get {
                return ResourceManager.GetString("AttendanceService.Delete.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the attendances/absences..
        /// </summary>
        public static string AttendanceService_DeleteMany_Failed {
            get {
                return ResourceManager.GetString("AttendanceService.DeleteMany.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attendances/absences which should be deleted could not be found..
        /// </summary>
        public static string AttendanceService_DeleteMany_NotFound {
            get {
                return ResourceManager.GetString("AttendanceService.DeleteMany.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the attendance/absence with the calendar date: &apos;{0}&apos;..
        /// </summary>
        public static string AttendanceService_GetByDate_Failed {
            get {
                return ResourceManager.GetString("AttendanceService.GetByDate.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attendance/absence with calendar date: &apos;{0}&apos; could be found..
        /// </summary>
        public static string AttendanceService_GetByDate_NotFound {
            get {
                return ResourceManager.GetString("AttendanceService.GetByDate.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the attendance/absence with the calendar day identifier: &apos;{0}&apos;..
        /// </summary>
        public static string AttendanceService_GetById_Failed {
            get {
                return ResourceManager.GetString("AttendanceService.GetById.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attendance/absence could be found with calendar day identifier: &apos;{0}&apos;..
        /// </summary>
        public static string AttendanceService_GetById_NotFound {
            get {
                return ResourceManager.GetString("AttendanceService.GetById.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the attendance entries based on the parameterization..
        /// </summary>
        public static string AttendanceService_GetPagedByParameters_Failed {
            get {
                return ResourceManager.GetString("AttendanceService.GetPagedByParameters.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attendance entries could be found based on the parameterization..
        /// </summary>
        public static string AttendanceService_GetPagedByParameters_NotFound {
            get {
                return ResourceManager.GetString("AttendanceService.GetPagedByParameters.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors in the update request, please check and correct..
        /// </summary>
        public static string AttendanceService_Update_BadRequest {
            get {
                return ResourceManager.GetString("AttendanceService.Update.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the attendance/absence..
        /// </summary>
        public static string AttendanceService_Update_Failed {
            get {
                return ResourceManager.GetString("AttendanceService.Update.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The presence/absence which should be updated could not be found..
        /// </summary>
        public static string AttendanceService_Update_NotFound {
            get {
                return ResourceManager.GetString("AttendanceService.Update.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the attendances/absences..
        /// </summary>
        public static string AttendanceService_UpdateMany_Failed {
            get {
                return ResourceManager.GetString("AttendanceService.UpdateMany.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attendances/absences which should be updated could not be found..
        /// </summary>
        public static string AttendanceService_UpdateMany_NotFound {
            get {
                return ResourceManager.GetString("AttendanceService.UpdateMany.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the user to the user role..
        /// </summary>
        public static string AuthenticationService_AddUserToRole_Failed {
            get {
                return ResourceManager.GetString("AuthenticationService.AddUserToRole.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to authenticate..
        /// </summary>
        public static string AuthenticationService_Authenticate_Failed {
            get {
                return ResourceManager.GetString("AuthenticationService.Authenticate.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to create the user..
        /// </summary>
        public static string AuthenticationService_CreateUser_Failed {
            get {
                return ResourceManager.GetString("AuthenticationService.CreateUser.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to add the roles for the user..
        /// </summary>
        public static string AuthenticationService_CreateUserRoles_Failed {
            get {
                return ResourceManager.GetString("AuthenticationService.CreateUserRoles.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the application users..
        /// </summary>
        public static string AuthenticationService_GetAll_Failed {
            get {
                return ResourceManager.GetString("AuthenticationService.GetAll.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the user with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string AuthenticationService_GetUserById_Failed {
            get {
                return ResourceManager.GetString("AuthenticationService.GetUserById.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the user with the name: &apos;{0}&apos;..
        /// </summary>
        public static string AuthenticationService_GetUserByName_Failed {
            get {
                return ResourceManager.GetString("AuthenticationService.GetUserByName.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the name: &apos;{0}&apos; could not be found..
        /// </summary>
        public static string AuthenticationService_GetUserByName_NotFound {
            get {
                return ResourceManager.GetString("AuthenticationService.GetUserByName.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing the user to the user role..
        /// </summary>
        public static string AuthenticationService_RemoveUserToRole_Failed {
            get {
                return ResourceManager.GetString("AuthenticationService.RemoveUserToRole.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role with the identifier: &apos;{0}&apos; could not be found..
        /// </summary>
        public static string AuthenticationService_RoleById_NotFound {
            get {
                return ResourceManager.GetString("AuthenticationService.RoleById.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update the user..
        /// </summary>
        public static string AuthenticationService_UpdateUser_Failed {
            get {
                return ResourceManager.GetString("AuthenticationService.UpdateUser.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the name &apos;{0}&apos; could not be authorized..
        /// </summary>
        public static string AuthenticationService_User_Unauthorized {
            get {
                return ResourceManager.GetString("AuthenticationService.User.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the user identifier: &apos;{0}&apos; could not be found..
        /// </summary>
        public static string AuthenticationService_UserById_NotFound {
            get {
                return ResourceManager.GetString("AuthenticationService.UserById.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the name: &apos;{0}&apos; could not be found..
        /// </summary>
        public static string AuthenticationService_UserByName_NotFound {
            get {
                return ResourceManager.GetString("AuthenticationService.UserByName.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the calendar day by date..
        /// </summary>
        public static string CalendarDayService_GetByDate_Failed {
            get {
                return ResourceManager.GetString("CalendarDayService.GetByDate.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No calendar day entry with the date: &apos;{0}&apos; could be found..
        /// </summary>
        public static string CalendarDayService_GetByDate_NotFound {
            get {
                return ResourceManager.GetString("CalendarDayService.GetByDate.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the calendar day by identifier..
        /// </summary>
        public static string CalendarDayService_GetById_Failed {
            get {
                return ResourceManager.GetString("CalendarDayService.GetById.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No calendar day entry with identifier: &apos;{0}&apos; could be found..
        /// </summary>
        public static string CalendarDayService_GetById_NotFound {
            get {
                return ResourceManager.GetString("CalendarDayService.GetById.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the current calendar day..
        /// </summary>
        public static string CalendarDayService_GetCurrentDate_Failed {
            get {
                return ResourceManager.GetString("CalendarDayService.GetCurrentDate.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current calendar day could not be found..
        /// </summary>
        public static string CalendarDayService_GetCurrentDate_NotFound {
            get {
                return ResourceManager.GetString("CalendarDayService.GetCurrentDate.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the calendar entries based on the parameterization..
        /// </summary>
        public static string CalendarDayService_GetPagedByParameters_Failed {
            get {
                return ResourceManager.GetString("CalendarDayService.GetPagedByParameters.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No calendar entries could be found based on the parameterization..
        /// </summary>
        public static string CalendarDayService_GetPagedByParameters_NotFound {
            get {
                return ResourceManager.GetString("CalendarDayService.GetPagedByParameters.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An guidernal error occurred while creating the bank card..
        /// </summary>
        public static string CardService_Create_Failed {
            get {
                return ResourceManager.GetString("CardService.Create.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An guidernal error occurred while deleting the bank card..
        /// </summary>
        public static string CardService_Delete_Failed {
            get {
                return ResourceManager.GetString("CardService.Delete.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bank account with the identifier: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string CardService_GetAccountById_NotFound {
            get {
                return ResourceManager.GetString("CardService.GetAccountById.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the bank cards..
        /// </summary>
        public static string CardService_GetAll_Failed {
            get {
                return ResourceManager.GetString("CardService.GetAll.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bank cards could be found to load..
        /// </summary>
        public static string CardService_GetAll_NotFound {
            get {
                return ResourceManager.GetString("CardService.GetAll.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the bank card with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string CardService_GetById_Failed {
            get {
                return ResourceManager.GetString("CardService.GetById.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bank card with the identifier: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string CardService_GetById_NotFound {
            get {
                return ResourceManager.GetString("CardService.GetById.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the bank card with the number: &apos;{0}&apos;..
        /// </summary>
        public static string CardService_GetByNumber_Failed {
            get {
                return ResourceManager.GetString("CardService.GetByNumber.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bank card with the number: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string CardService_GetByNumber_NotFound {
            get {
                return ResourceManager.GetString("CardService.GetByNumber.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank card with the number: &apos;{0}&apos; already exists..
        /// </summary>
        public static string CardService_Number_Conflict {
            get {
                return ResourceManager.GetString("CardService.Number.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An guidernal error occurred while updating the bank card..
        /// </summary>
        public static string CardService_Update_Failed {
            get {
                return ResourceManager.GetString("CardService.Update.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the card type enumerators..
        /// </summary>
        public static string EnumeratorService_GetCardTypes_Failed {
            get {
                return ResourceManager.GetString("EnumeratorService.GetCardTypes.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the day type enumerators..
        /// </summary>
        public static string EnumeratorService_GetDayTypes_Failed {
            get {
                return ResourceManager.GetString("EnumeratorService.GetDayTypes.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the role type enumerators..
        /// </summary>
        public static string EnumeratorService_GetRoleTypes_Failed {
            get {
                return ResourceManager.GetString("EnumeratorService.GetRoleTypes.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the work day type enumerators..
        /// </summary>
        public static string EnumeratorService_WorkDayTypes_Failed {
            get {
                return ResourceManager.GetString("EnumeratorService.WorkDayTypes.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the transaction for the account with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string TransactionServiceErrors_CreateForAccount_Failed {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.CreateForAccount.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the transaction for the card with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string TransactionServiceErrors_CreateForCard_Failed {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.CreateForCard.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the transaction with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string TransactionServiceErrors_Delete_Failed {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.Delete.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the transaction for the bank account with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string TransactionServiceErrors_GetByAccountId_Failed {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.GetByAccountId.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions for the bank account with the identifier: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string TransactionServiceErrors_GetByAccountId_NotFound {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.GetByAccountId.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the transaction for the bank card with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string TransactionServiceErrors_GetByCardId_Failed {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.GetByCardId.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions for the bank card with the identifier: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string TransactionServiceErrors_GetByCardId_NotFound {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.GetByCardId.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the bank transaction with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string TransactionServiceErrors_GetById_Failed {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.GetById.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bank transaction with the identifier: &apos;{0}&apos; could be found to load..
        /// </summary>
        public static string TransactionServiceErrors_GetById_NotFound {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.GetById.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the transaction with the identifier: &apos;{0}&apos;..
        /// </summary>
        public static string TransactionServiceErrors_Update_Failed {
            get {
                return ResourceManager.GetString("TransactionServiceErrors.Update.Failed", resourceCulture);
            }
        }
    }
}
