name: Continuous Integration

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5

    - name: Setup MSSQL
      uses: potatoqualitee/mssqlsuite@v1.11
      with:
        install: localdb
    
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration release --verbosity minimal
    
    - name: Test
      run: dotnet test --no-build --configuration release --verbosity minimal
